# Generated by Django 4.1.6 on 2023-02-05 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0003_alter_categoria_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aluraflix.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='A Cor precisa estar em código Hexadecimal (#FFFFFF | #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor'),
        ),
    ]
