# Generated by Django 4.1.6 on 2023-02-05 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0004_video_categoria_alter_categoria_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='A Cor precisa estar em código Hexadecimal (#FFFFFF | #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Cor'),
        ),
    ]
